version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
      #- .:/var/www/html

  # 追記
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      #- .:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work